<?php
// Automatically Generated by TestLink Installer - Thu, 22 Nov 18 21:50:24 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin12345');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
